(() => {
  const $ = id => document.getElementById(id);
  const canvas = $("game"), ctx = canvas.getContext("2d"), W = canvas.width, H = canvas.height;
  const ui = {start:$("startScreen"), over:$("gameOverScreen"), hud:$("hud"), score:$("score"), high:$("highScore"), sideScore:$("sideScore"), sideHigh:$("sideHigh"), level:$("level"), sideLevel:$("sideLevel"), progress:$("progressBar"), progressText:$("progressText"), final:$("finalScore"), record:$("recordMessage"), pause:$("pauseBtn"), pauseTag:$("pauseTag"), toast:$("toast"), soundLabel:$("soundLabel")};
  let state="menu", score=0, high=0, elapsed=0, last=0, spawn=0, crystalSpawn=0, combo=0, comboTime=0, sound=true, audio=null;
  try { high=Number(localStorage.getItem("neonCometHigh")||0); } catch {}
  const keys=new Set(), stars=Array.from({length:115},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.8+.3,v:12+Math.random()*45,a:.2+Math.random()*.7}));
  let asteroids=[], crystals=[], particles=[], popups=[];
  const ship={x:W/2,y:H*.73,r:11,speed:300,trail:[],inv:0};
  const rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function audioInit(){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)(); if(audio.state==="suspended")audio.resume();}catch{}}
  function beep(freq=440,dur=.08,type="sine",vol=.035){if(!sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
  function toast(s){ui.toast.textContent=s;ui.toast.classList.add("show");setTimeout(()=>ui.toast.classList.remove("show"),850)}
  function updateUI(){const s=String(Math.floor(score)).padStart(6,"0"),h=String(high).padStart(6,"0"),sector=1+Math.floor(score/1000);ui.score.textContent=ui.sideScore.textContent=s;ui.high.textContent=ui.sideHigh.textContent=h;ui.level.textContent="SECTOR "+String(sector).padStart(2,"0");ui.sideLevel.textContent=String(sector).padStart(2,"0");ui.progress.style.width=(score%1000/10)+"%";ui.progressText.textContent=Math.floor(score%1000/10)+"%";}
  function reset(){score=0;elapsed=0;spawn=.7;crystalSpawn=1.5;combo=0;comboTime=0;asteroids=[];crystals=[];particles=[];popups=[];ship.x=W/2;ship.y=H*.73;ship.inv=1.5;ship.trail=[];updateUI();}
  function start(){audioInit();reset();state="playing";ui.start.hidden=true;ui.over.hidden=true;ui.hud.hidden=false;ui.pause.disabled=false;ui.pause.textContent="Ⅱ PAUSAR";ui.pauseTag.hidden=true;beep(600,.13,"triangle");}
  function togglePause(){if(state==="playing"){state="paused";ui.pauseTag.hidden=false;ui.pause.textContent="▶ SEGUIR"}else if(state==="paused"){state="playing";ui.pauseTag.hidden=true;ui.pause.textContent="Ⅱ PAUSAR";last=0}}
  function end(){state="over";ui.over.hidden=false;ui.pause.disabled=true;ui.final.textContent=Math.floor(score).toLocaleString("es-MX");if(score>high){high=Math.floor(score);try{localStorage.setItem("neonCometHigh",high)}catch{}ui.record.textContent="¡NUEVO RÉCORD! El cosmos es tuyo.";beep(180,.35,"sawtooth")}else{ui.record.textContent="El cosmos te espera de nuevo.";beep(110,.3,"triangle")}updateUI();}
  function burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(35,190);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.25,.8),max:.8,r:rand(1,3),color})}}
  function popup(x,y,text,color){popups.push({x,y,text,color,life:.8})}
  function spawnRock(){const r=rand(13,29),s=rand(90,150)+Math.min(150,elapsed*2);const n=Array.from({length:9},()=>rand(.72,1.2));asteroids.push({x:rand(r,W-r),y:-r,r,vy:s,vx:rand(-35,35),rot:rand(0,6),spin:rand(-2,2),points:n.map((v,i)=>({a:i*Math.PI*2/n.length,r:r*v}))})}
  function spawnCrystal(){crystals.push({x:rand(24,W-24),y:-15,r:9,vy:rand(90,130),phase:0,spin:0})}
  function hit(a,b,r){return Math.hypot(a.x-b.x,a.y-b.y)<r}
  function update(dt){
    elapsed+=dt;ship.inv=Math.max(0,ship.inv-dt);comboTime-=dt;if(comboTime<=0)combo=0;
    let dx=(keys.has("ArrowRight")||keys.has("d")||keys.has("D")?1:0)-(keys.has("ArrowLeft")||keys.has("a")||keys.has("A")?1:0),dy=(keys.has("ArrowDown")||keys.has("s")||keys.has("S")?1:0)-(keys.has("ArrowUp")||keys.has("w")||keys.has("W")?1:0);
    if(pointer.active){ship.x+=(pointer.x-ship.x)*Math.min(1,dt*8);ship.y+=(pointer.y-ship.y)*Math.min(1,dt*8)}else{const mag=Math.hypot(dx,dy)||1;ship.x+=dx/mag*ship.speed*dt;ship.y+=dy/mag*ship.speed*dt}
    ship.x=clamp(ship.x,16,W-16);ship.y=clamp(ship.y,24,H-16);ship.trail.push({x:ship.x,y:ship.y+13,life:.28});ship.trail=ship.trail.filter(t=>(t.life-=dt)>0);
    spawn-=dt;if(spawn<=0){spawnRock();spawn=Math.max(.22, .78-elapsed*.005)}crystalSpawn-=dt;if(crystalSpawn<=0){spawnCrystal();crystalSpawn=rand(1.1,1.9)}
    score+=dt*(2+Math.floor(elapsed/18));if(Math.floor(score/1000)>Math.floor((score-dt*(2+Math.floor(elapsed/18)))/1000))toast("SECTOR SUPERADO");
    for(let i=asteroids.length-1;i>=0;i--){const a=asteroids[i];a.y+=a.vy*dt;a.x+=a.vx*dt;a.rot+=a.spin*dt;if(a.y>H+a.r){asteroids.splice(i,1);continue}if(!ship.inv&&hit(ship,a,ship.r+a.r*.7)){burst(ship.x,ship.y,"#ff5da2",30);end();return}}
    for(let i=crystals.length-1;i>=0;i--){const c=crystals[i];c.y+=c.vy*dt;c.phase+=dt*4;c.spin+=dt*2;if(c.y>H+20){crystals.splice(i,1);continue}if(hit(ship,c,ship.r+c.r+3)){crystals.splice(i,1);combo=comboTime>0?combo+1:1;comboTime=2.2;const pts=100*Math.min(combo,5);score+=pts;burst(c.x,c.y,"#62f5ed",16);popup(c.x,c.y-8,"+"+pts+(combo>1?" ×"+Math.min(combo,5):""),"#62f5ed");beep(520+Math.min(combo,5)*90,.12);}}
    particles=particles.filter(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.08,dt);p.vy*=Math.pow(.08,dt);p.life-=dt;return p.life>0});popups=popups.filter(p=>{p.y-=28*dt;p.life-=dt;return p.life>0});for(const s of stars){s.y+=s.v*dt;if(s.y>H)s.y=0}updateUI();
  }
  function drawShip(){ctx.save();ctx.translate(ship.x,ship.y);ctx.shadowBlur=18;ctx.shadowColor="#62f5ed";ctx.fillStyle="#62f5ed";ctx.beginPath();ctx.moveTo(0,-17);ctx.lineTo(12,12);ctx.lineTo(0,7);ctx.lineTo(-12,12);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(4,4);ctx.lineTo(0,2);ctx.lineTo(-4,4);ctx.fill();ctx.fillStyle="#ff5da2";ctx.beginPath();ctx.moveTo(-4,10);ctx.lineTo(0,rand(17,25));ctx.lineTo(4,10);ctx.fill();ctx.restore()}
  function render(){ctx.fillStyle="#080b20";ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.53,H*.44,10,W*.53,H*.44,H*.7);g.addColorStop(0,"#17183a");g.addColorStop(1,"#080b20");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle="#c9e8ff";ctx.fillRect(s.x,s.y,s.r,s.r*1.8)}ctx.globalAlpha=1;ctx.strokeStyle="#4e5a9a13";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
    for(const c of crystals){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.spin);ctx.scale(1+Math.sin(c.phase)*.18,1+Math.sin(c.phase)*.18);ctx.shadowBlur=20;ctx.shadowColor="#62f5ed";ctx.fillStyle="#62f5ed";ctx.beginPath();ctx.moveTo(0,-c.r);ctx.lineTo(c.r*.72,0);ctx.lineTo(0,c.r);ctx.lineTo(-c.r*.72,0);ctx.fill();ctx.restore()}
    for(const a of asteroids){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.rot);ctx.fillStyle="#292d4c";ctx.strokeStyle="#ff7ba6";ctx.lineWidth=1.4;ctx.beginPath();a.points.forEach((p,i)=>{const x=Math.cos(p.a)*p.r,y=Math.sin(p.a)*p.r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
    for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const p of popups){ctx.globalAlpha=clamp(p.life/.8,0,1);ctx.fillStyle=p.color;ctx.font="bold 15px 'DM Mono',monospace";ctx.textAlign="center";ctx.fillText(p.text,p.x,p.y)}ctx.globalAlpha=1;if(state!=="menu"||!ui.start.hidden)drawShip();}
  function frame(now){const dt=Math.min(.033,Math.max(0,(now-(last||now))/1000));last=now;if(state==="playing")update(dt);else if(state==="menu"){elapsed+=dt;for(const s of stars){s.y+=s.v*.15*dt;if(s.y>H)s.y=0}ship.x=W/2+Math.sin(elapsed*.65)*80;ship.y=H*.72+Math.sin(elapsed*1.1)*10}render();requestAnimationFrame(frame)}
  const pointer={active:false,x:W/2,y:H/2};function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
  canvas.addEventListener("pointerdown",e=>{if(state!=="playing")return;pointer.active=true;Object.assign(pointer,point(e));canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(pointer.active)Object.assign(pointer,point(e))});for(const ev of ["pointerup","pointercancel"])canvas.addEventListener(ev,()=>pointer.active=false);
  window.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys.add(e.key);if(e.key.toLowerCase()==="p"&&(state==="playing"||state==="paused"))togglePause();if(e.key===" "&&(state==="menu"||state==="over"))start()});window.addEventListener("keyup",e=>keys.delete(e.key));window.addEventListener("blur",()=>{keys.clear();pointer.active=false;if(state==="playing")togglePause()});
  $("startBtn").addEventListener("click",start);$("restartBtn").addEventListener("click",start);ui.pause.addEventListener("click",togglePause);$("soundToggle").addEventListener("click",()=>{sound=!sound;ui.soundLabel.textContent=sound?"SONIDO ON":"SONIDO OFF";if(sound){audioInit();beep(520,.08)}});
  updateUI();render();requestAnimationFrame(frame);
})();